apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-todoapp-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
