{{- if .Values.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv-data
  labels:
    pv-name: {{ .Chart.Name }}-pv-data
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.pv.capacity }}
  hostPath:
    path: /data/
{{- end }}