apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc-data
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      pv-name: {{ .Chart.Name }}-pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}