secrets:
  SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-!dkpebxsz^dg47x)-k&kq_3zf*9j*"
  DB_NAME: "app_db"
  DB_USER: "app_user"
  DB_PASSWORD: "1234"
  DB_HOST: "mysql-0.mysql.mysql.svc.cluster.local"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  repository: bohdansukhy/todoapp
  tag: "3.0.1"

affinity:
  nodeAffinity:
    key: "app"
    values:
      - kube2py

serviceAccount:
  name: secrets-reader

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70
  targetMemory: 70

pv:
  enabled: true
  capacity: 1Gi

pvc:
  storage: 1Gi

serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  interval: 10s
  path: /metrics
  port: http